import numpy as np
print ('')
print ('La matriz A')
A=np.array([[1,2,-1],[2,-1,0],[-1,3,1]])
print (A)
print ('')
B=np.linalg.inv(A)
C=A.dot(B)
print ('La matriz inversa de A')
print (B)
print ('')
print ('La matriz unitaria C')
print (C)


#print ('')
#print ('La matriz D')
#D=np.array([[-1,3,4],[1,-2,5],[-3,7,5]])
#E=np.linalg.inv(D)
#F=E.dot(D)
#print ('La matriz inversa de D')
#print (E)
#print ('')
#print ('La matriz unitaria F')
#print (F)
